name: Deploy to Azure VM
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 172.174.163.45
          key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
          username: fpochat
          password: ${{ secrets.VM_PASSWORD }}
          script: cd docker-frontend
